# Generated by Django 2.1.5 on 2022-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_link', models.CharField(max_length=5000)),
            ],
        ),
    ]
